### ISSUE TITLE
benchmark fixtures used incorrectly

### ISSUE THREAD

**Issue by elidoran** [blakeembrey/array-flatten#15]
The `benchmarked` library checks ([here](https://github.com/jonschlinkert/benchmarked/blob/master/index.js#L297-L302)) if the first arg is an array. When it is, it provides the args array as the arguments. Essentially unwrapping your fixture.

It appears you knew that and were dealing with it in [here](https://github.com/blakeembrey/array-flatten/blob/master/benchmark/index.js#L18-L20), and [here](https://github.com/blakeembrey/array-flatten/blob/master/benchmark/index.js#L40-L42).

It seems that no longer works tho. Those functions don't get called and the target functions are called with extra, unintended, arguments.

I noticed this when the "if-depth" benchmark was way faster than the others. I had it show its arguments the first time it ran and it was receiving a `'b'` as the second arg. When I looked at "fixtures/large.js" I found that was the second element in the exported (outermost) array.

If I alter your fixtures files to wrap their exported value an extra time then they are used correctly for the flatten suite, but not the arguments/depth suites.

After looking at the source code for `benchmarked` I haven't seen a way to provide a similar option which will run those "extra wrapping" functions you have.

So, what I've done, for now, is put the current fixtures into a sub-directory named "fixtures/arguments", similar to "code/arguments". Then, created corresponding files in "fixtures/flatten" and "fixtures/depth" which require the ones in "fixtures/arguments" and wraps them. The "flatten" ones are only wrapped into an array. The "depth" ones are wrapped and a second element of `4` provided; same as what you had in the benchmark main file.

**Comment by blakeembrey** [comment]
Welcome to accepting a PR. I might have missed the changelog when I merged https://github.com/blakeembrey/array-flatten/commit/e45559de262269799253185026220eae106d8860.

**Comment by blakeembrey** [comment]
I'd also be down to replace this with either raw code (e.g. https://github.com/blakeembrey/free-style/blob/master/benchmarks/index.ts) or use benchmark.js directly.

**Comment by elidoran** [comment]
I'll supply a PR with the fix.

I also struggle with the whole do I use "custom testing", "benchmarkjs", "or something else". :)

**Comment by shaoron** [comment]
Let me complete this task

**Comment by blakeembrey** [comment]
Fixed as part of https://github.com/blakeembrey/array-flatten/commit/8de93a162b995af9afbda58bdee2d8899ddf5b8b.
