### ISSUE TITLE
Passing a single string results in an array with an index for each character.

### ISSUE THREAD

**Issue by dominicbarnes** [blakeembrey/array-flatten#3]
Since internally, this is assumed to be an array, (or at least array-like) it takes a string like `abc` and creates `[ 'a', 'b', 'c' ]`. This forces me to always wrap my arguments in an array literal:

```js
flatten('abc');
// [ 'a', 'b', 'c' ]

flatten([ 'abc' ]);
// [ 'abc' ]
```

Would it be all right if strings were a special case that are assumed to be an array element? My hunch is that this is what most people would expect with strings, but I could be wrong.

**Comment by blakeembrey** [comment]
Hi! I might have missed the use-case entirely from this, but why? What's the reason for using non-arrays and expecting a different behavior? If anything, I should probably be throwing an error on non-array input.

**Comment by dominicbarnes** [comment]
Haha, yeah I totally understand the rationale behind throwing. That would have at least helped me catch this logic error earlier.

My use-case is where I'm using an arbitrary list of file extensions that a specific batch of code applies to:

```js
builder.stat('js', statFile);
builder.stat([ 'js', 'css' ], statFile);
```

I mainly wanted to make that first argument pretty flexible, allowing people to specify a single extension, an array of extensions, or a crazy conglomeration of nested arrays depending on where exactly the data comes from.

All in all, I'm fine with throwing on non-arrays. (I just got a little confused when "js" became "j" and "s" the first time)

**Comment by blakeembrey** [comment]
@dominicbarnes Sorry for the delay, I just pushed `v2.0.0` to NPM with error validation. I kept the old method around as `flatten.from` which is consistent naming with the `Array.from` function.
