### ISSUE TITLE
Please ship the typings with npm

### ISSUE THREAD

**Issue by sebilasse** [blakeembrey/array-flatten#6]
Hey there,

could you please either ship the `.d.ts` with npm or register it ?

**Comment by blakeembrey** [comment]
It is.

![image](https://cloud.githubusercontent.com/assets/1088987/19199377/9da303ec-8c78-11e6-8631-27db4d64ea9f.png)

**Comment by sebilasse** [comment]
uuups. Wrong version number in package.json. Sorry. Have a nice day.
